# Generated by Django 5.0.9 on 2024-11-12 10:38

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitiativePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='InitiativeDetails',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('always_open', models.BooleanField(default=False, help_text='Open 24/7', verbose_name='Always open')),
                ('area', models.CharField(blank=True, help_text='City district', max_length=255, verbose_name='City district')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('description', wagtail.fields.RichTextField(blank=True, max_length=32767, verbose_name='Description')),
                ('email', models.CharField(blank=True, max_length=127, null=True, verbose_name='Email')),
                ('facebook', models.CharField(blank=True, help_text='Link to Facebook page', max_length=1023, null=True, verbose_name='Facebook')),
                ('phone', models.CharField(blank=True, max_length=127, null=True, verbose_name='Phone number')),
                ('short_description', models.CharField(blank=True, max_length=100, verbose_name='Short description')),
                ('website', models.URLField(blank=True, max_length=1023, null=True, verbose_name='Website')),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Main image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
